# Generated by Django 4.0.4 on 2022-06-14 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_id', models.IntegerField()),
                ('guide_name', models.CharField(max_length=200)),
                ('experience', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('contact_no', models.IntegerField()),
                ('no_of_routes', models.IntegerField()),
                ('review', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.IntegerField()),
                ('package_name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.IntegerField()),
                ('destination', models.CharField(max_length=200)),
                ('ticket_type', models.CharField(max_length=200)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.guide')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.package')),
            ],
        ),
        migrations.CreateModel(
            name='agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.IntegerField()),
                ('agency_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.package')),
            ],
        ),
    ]
